<?php

namespace MediaLibrary\Domain\Model\Media;

use MediaLibrary\Domain\Model\Media\om\BaseMediaQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'media_library_media_common' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Sep 24 17:02:25 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.Media
 */
class MediaQuery extends BaseMediaQuery
{
}
