<?php

namespace MediaLibrary\Domain\Model\User;

use MediaLibrary\Domain\Model\User\om\BaseIdentity;


/**
 * Skeleton subclass for representing a row from the 'media_library_user_identities' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Sep 24 17:02:25 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.User
 */
class Identity extends BaseIdentity
{
}
