<?php

namespace MediaLibrary\Domain\Model\Media\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'media_library_media_common' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Sep 24 17:02:43 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.Media.map
 */
class MediaTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'Media.map.MediaTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('media_library_media_common');
        $this->setPhpName('Media');
        $this->setClassname('MediaLibrary\\Domain\\Model\\Media\\Media');
        $this->setPackage('Media');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'CHAR', true, 36, null);
        $this->addForeignKey('distributor_id', 'DistributorId', 'CHAR', 'media_library_media_distributor', 'id', true, 36, null);
        $this->addForeignKey('edition_id', 'EditionId', 'CHAR', 'media_library_media_edition', 'id', true, 36, null);
        $this->addForeignKey('type_id', 'TypeId', 'CHAR', 'media_library_media_type', 'id', true, 36, null);
        $this->addForeignKey('user_id', 'UserId', 'CHAR', 'media_library_user_users', 'id', true, 36, null);
        $this->addColumn('age_limit', 'AgeLimit', 'TINYINT', true, 2, 0);
        $this->addColumn('create_date', 'CreateDate', 'TIMESTAMP', true, null, 'CURRENT_TIMESTAMP');
        $this->addColumn('release_date', 'ReleaseDate', 'TIMESTAMP', true, null, '0000-00-00 00:00:00');
        $this->addColumn('name', 'Name', 'VARCHAR', true, 120, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Distributor', 'MediaLibrary\\Domain\\Model\\Media\\Distributor', RelationMap::MANY_TO_ONE, array('distributor_id' => 'id', ), null, null);
        $this->addRelation('Edition', 'MediaLibrary\\Domain\\Model\\Media\\Edition', RelationMap::MANY_TO_ONE, array('edition_id' => 'id', ), null, null);
        $this->addRelation('Type', 'MediaLibrary\\Domain\\Model\\Media\\Type', RelationMap::MANY_TO_ONE, array('type_id' => 'id', ), null, null);
        $this->addRelation('User', 'MediaLibrary\\Domain\\Model\\User\\User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
        $this->addRelation('Audio', 'MediaLibrary\\Domain\\Model\\Media\\Audio', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Audios');
        $this->addRelation('Book', 'MediaLibrary\\Domain\\Model\\Media\\Book', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Books');
        $this->addRelation('Video', 'MediaLibrary\\Domain\\Model\\Media\\Video', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Videos');
        $this->addRelation('Game', 'MediaLibrary\\Domain\\Model\\Media\\Game', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Games');
        $this->addRelation('Comment', 'MediaLibrary\\Domain\\Model\\Media\\Comment', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'Comments');
        $this->addRelation('MediaToArtist', 'MediaLibrary\\Domain\\Model\\Media\\MediaToArtist', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToArtists');
        $this->addRelation('MediaToGenre', 'MediaLibrary\\Domain\\Model\\Media\\MediaToGenre', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToGenres');
        $this->addRelation('MediaToLanguage', 'MediaLibrary\\Domain\\Model\\Media\\MediaToLanguage', RelationMap::ONE_TO_MANY, array('id' => 'media_id', ), null, null, 'MediaToLanguages');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'create_entity' =>  array (
),
            'add_to_entity_instantiator' =>  array (
  'entity_add_to_entity_instantiator' => 'true',
  'entity_instantiator_class_name' => 'EntityInstantiator',
  'entity_instantiator_indention' => '    ',
  'entity_instantiator_namespace' => 'MediaLibrary\\Application\\Service',
  'entity_instantiator_path_to_output' => 'source/MediaLibrary/Application/Service',
  'entity_method_name_prefix' => 'create',
),
        );
    } // getBehaviors()

} // MediaTableMap
