<?php

namespace MediaLibrary\Domain\Model\User\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'media_library_user_users' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Sep 24 17:02:43 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.User.map
 */
class UserTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'User.map.UserTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('media_library_user_users');
        $this->setPhpName('User');
        $this->setClassname('MediaLibrary\\Domain\\Model\\User\\User');
        $this->setPackage('User');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'CHAR', true, 36, null);
        $this->addColumn('firstName', 'Firstname', 'VARCHAR', true, 40, null);
        $this->addColumn('lastName', 'Lastname', 'VARCHAR', true, 40, null);
        $this->addColumn('email', 'Email', 'VARCHAR', true, 80, null);
        $this->addColumn('is_active', 'IsActive', 'BOOLEAN', true, 1, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Identity', 'MediaLibrary\\Domain\\Model\\User\\Identity', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'Identitys');
        $this->addRelation('Media', 'MediaLibrary\\Domain\\Model\\Media\\Media', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'Medias');
        $this->addRelation('Comment', 'MediaLibrary\\Domain\\Model\\Media\\Comment', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null, 'Comments');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'create_entity' =>  array (
),
            'add_to_entity_instantiator' =>  array (
  'entity_add_to_entity_instantiator' => 'true',
  'entity_instantiator_class_name' => 'EntityInstantiator',
  'entity_instantiator_indention' => '    ',
  'entity_instantiator_namespace' => 'MediaLibrary\\Application\\Service',
  'entity_instantiator_path_to_output' => 'source/MediaLibrary/Application/Service',
  'entity_method_name_prefix' => 'create',
),
        );
    } // getBehaviors()

} // UserTableMap
