<?php

namespace MediaLibrary\Domain\Model\User\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'media_library_user_identities' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Thu Sep 24 17:02:42 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.User.map
 */
class IdentityTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'User.map.IdentityTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('media_library_user_identities');
        $this->setPhpName('Identity');
        $this->setClassname('MediaLibrary\\Domain\\Model\\User\\Identity');
        $this->setPackage('User');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'CHAR', true, 36, null);
        $this->addColumn('login', 'Login', 'VARCHAR', true, 40, null);
        $this->addColumn('password', 'Password', 'CHAR', true, 40, null);
        $this->addForeignKey('user_id', 'UserId', 'CHAR', 'media_library_user_users', 'id', true, 36, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('User', 'MediaLibrary\\Domain\\Model\\User\\User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'create_entity' =>  array (
),
            'add_to_entity_instantiator' =>  array (
  'entity_add_to_entity_instantiator' => 'true',
  'entity_instantiator_class_name' => 'EntityInstantiator',
  'entity_instantiator_indention' => '    ',
  'entity_instantiator_namespace' => 'MediaLibrary\\Application\\Service',
  'entity_instantiator_path_to_output' => 'source/MediaLibrary/Application/Service',
  'entity_method_name_prefix' => 'create',
),
        );
    } // getBehaviors()

} // IdentityTableMap
